/*
  # Fx Flow Scalper V2.0 Strategy Tables

  1. New Tables
    - `strategy_signals`: Stores all trade signals generated by the strategy
    - `ai_demo_trades`: Tracks parallel demo positions for AI learning
    - `strategy_performance`: Aggregates performance metrics by strategy version
    - `auto_trading_sessions`: Manages automatic trading state
    - `user_trade_execution`: Links user trades to AI recommendations

  2. Security
    - Enable RLS on all new tables
    - Policies restrict access to authenticated users viewing their own data

  3. Indexes
    - Performance indexes on symbol, timestamp, user_id for fast queries
*/

-- Strategy Signals Table
CREATE TABLE IF NOT EXISTS strategy_signals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_version text NOT NULL DEFAULT 'Fx Flow Scalper v2.0',
  symbol text NOT NULL,
  timeframe text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('BUY', 'SELL')),
  entry_price decimal(15,8) NOT NULL,
  stop_loss decimal(15,8) NOT NULL,
  take_profit decimal(15,8) NOT NULL,
  risk_reward decimal(5,2) NOT NULL,
  confidence integer NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
  approved boolean DEFAULT false,
  executed boolean DEFAULT false,
  signal_type text NOT NULL CHECK (signal_type IN ('prompt', 'automatic', 'manual')),
  phase1_passed boolean NOT NULL DEFAULT false,
  phase1_bias text,
  phase1_confidence integer,
  phase1_reason text,
  phase2_passed boolean NOT NULL DEFAULT false,
  phase2_confidence integer,
  phase2_reason text,
  phase3_passed boolean NOT NULL DEFAULT false,
  phase3_confidence integer,
  phase3_reason text,
  reasoning jsonb DEFAULT '[]',
  notes text,
  created_at timestamptz DEFAULT now(),
  expires_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_strategy_signals_user_symbol ON strategy_signals(user_id, symbol);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_created ON strategy_signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_strategy_signals_approved ON strategy_signals(approved, executed);

-- AI Demo Trades Table
CREATE TABLE IF NOT EXISTS ai_demo_trades (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  signal_id uuid REFERENCES strategy_signals(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  symbol text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('BUY', 'SELL')),
  entry_price decimal(15,8) NOT NULL,
  stop_loss decimal(15,8) NOT NULL,
  take_profit decimal(15,8) NOT NULL,
  lot_size decimal(10,2) NOT NULL,
  entry_time timestamptz NOT NULL DEFAULT now(),
  exit_time timestamptz,
  exit_price decimal(15,8),
  pnl decimal(15,2),
  pnl_pips decimal(10,2),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'stopped', 'target_hit')),
  is_ai_trade boolean DEFAULT true,
  confidence integer NOT NULL,
  strategy_version text NOT NULL DEFAULT 'Fx Flow Scalper v2.0',
  learning_metadata jsonb DEFAULT '{}',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_demo_trades_user ON ai_demo_trades(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_demo_trades_signal ON ai_demo_trades(signal_id);
CREATE INDEX IF NOT EXISTS idx_ai_demo_trades_status ON ai_demo_trades(status);
CREATE INDEX IF NOT EXISTS idx_ai_demo_trades_entry_time ON ai_demo_trades(entry_time DESC);

-- Strategy Performance Table
CREATE TABLE IF NOT EXISTS strategy_performance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_version text NOT NULL DEFAULT 'Fx Flow Scalper v2.0',
  period text NOT NULL CHECK (period IN ('daily', 'weekly', 'monthly', 'all-time')),
  period_start timestamptz NOT NULL,
  period_end timestamptz NOT NULL,
  total_trades integer DEFAULT 0,
  winning_trades integer DEFAULT 0,
  losing_trades integer DEFAULT 0,
  win_rate decimal(5,2) DEFAULT 0,
  average_rr decimal(5,2) DEFAULT 0,
  profit_factor decimal(10,2) DEFAULT 0,
  total_pnl decimal(15,2) DEFAULT 0,
  average_win decimal(15,2) DEFAULT 0,
  average_loss decimal(15,2) DEFAULT 0,
  max_drawdown decimal(15,2) DEFAULT 0,
  best_trade decimal(15,2) DEFAULT 0,
  worst_trade decimal(15,2) DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, strategy_version, period, period_start)
);

CREATE INDEX IF NOT EXISTS idx_strategy_performance_user_period ON strategy_performance(user_id, period, period_start DESC);

-- Auto Trading Sessions Table
CREATE TABLE IF NOT EXISTS auto_trading_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  enabled boolean DEFAULT false,
  max_daily_trades integer DEFAULT 6,
  trades_taken_today integer DEFAULT 0,
  min_confidence integer DEFAULT 75,
  risk_percentage decimal(5,2) DEFAULT 1.0,
  active_symbols text[] DEFAULT '{}',
  trading_hours_start time DEFAULT '00:00:00',
  trading_hours_end time DEFAULT '23:59:59',
  last_trade_time timestamptz,
  session_start timestamptz,
  session_end timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id)
);

-- User Trade Execution Table
CREATE TABLE IF NOT EXISTS user_trade_execution (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  signal_id uuid REFERENCES strategy_signals(id) ON DELETE SET NULL,
  ai_demo_trade_id uuid REFERENCES ai_demo_trades(id) ON DELETE SET NULL,
  symbol text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('BUY', 'SELL')),
  recommended_entry decimal(15,8),
  actual_entry decimal(15,8) NOT NULL,
  recommended_sl decimal(15,8),
  actual_sl decimal(15,8),
  recommended_tp decimal(15,8),
  actual_tp decimal(15,8),
  exit_price decimal(15,8),
  user_pnl decimal(15,2),
  ai_pnl decimal(15,2),
  followed_recommendation boolean DEFAULT false,
  execution_time timestamptz DEFAULT now(),
  exit_time timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_trade_execution_user ON user_trade_execution(user_id);
CREATE INDEX IF NOT EXISTS idx_user_trade_execution_signal ON user_trade_execution(signal_id);

-- Enable Row Level Security
ALTER TABLE strategy_signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_demo_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategy_performance ENABLE ROW LEVEL SECURITY;
ALTER TABLE auto_trading_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_trade_execution ENABLE ROW LEVEL SECURITY;

-- RLS Policies for strategy_signals
CREATE POLICY "Users can view own strategy signals"
  ON strategy_signals FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own strategy signals"
  ON strategy_signals FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own strategy signals"
  ON strategy_signals FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- RLS Policies for ai_demo_trades
CREATE POLICY "Users can view own AI demo trades"
  ON ai_demo_trades FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own AI demo trades"
  ON ai_demo_trades FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own AI demo trades"
  ON ai_demo_trades FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- RLS Policies for strategy_performance
CREATE POLICY "Users can view own strategy performance"
  ON strategy_performance FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own strategy performance"
  ON strategy_performance FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own strategy performance"
  ON strategy_performance FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- RLS Policies for auto_trading_sessions
CREATE POLICY "Users can view own auto trading sessions"
  ON auto_trading_sessions FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own auto trading sessions"
  ON auto_trading_sessions FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own auto trading sessions"
  ON auto_trading_sessions FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- RLS Policies for user_trade_execution
CREATE POLICY "Users can view own trade execution"
  ON user_trade_execution FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own trade execution"
  ON user_trade_execution FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own trade execution"
  ON user_trade_execution FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Function to update strategy performance automatically
CREATE OR REPLACE FUNCTION update_strategy_performance()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO strategy_performance (
    user_id, strategy_version, period, period_start, period_end,
    total_trades, winning_trades, losing_trades
  )
  VALUES (
    NEW.user_id, NEW.strategy_version, 'daily',
    DATE_TRUNC('day', NEW.exit_time),
    DATE_TRUNC('day', NEW.exit_time) + INTERVAL '1 day',
    1,
    CASE WHEN NEW.pnl > 0 THEN 1 ELSE 0 END,
    CASE WHEN NEW.pnl < 0 THEN 1 ELSE 0 END
  )
  ON CONFLICT (user_id, strategy_version, period, period_start)
  DO UPDATE SET
    total_trades = strategy_performance.total_trades + 1,
    winning_trades = strategy_performance.winning_trades + (CASE WHEN NEW.pnl > 0 THEN 1 ELSE 0 END),
    losing_trades = strategy_performance.losing_trades + (CASE WHEN NEW.pnl < 0 THEN 1 ELSE 0 END),
    total_pnl = strategy_performance.total_pnl + NEW.pnl,
    updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger on ai_demo_trades to update performance
CREATE TRIGGER update_performance_on_trade_close
  AFTER UPDATE OF status ON ai_demo_trades
  FOR EACH ROW
  WHEN (NEW.status IN ('closed', 'stopped', 'target_hit') AND OLD.status = 'open')
  EXECUTE FUNCTION update_strategy_performance();