import { supabase } from '../lib/supabase';

/**
 * Auto-Backtest Job Monitor
 *
 * This service monitors the auto_backtest_queue for pending jobs
 * and triggers the executor Edge Function when jobs are found.
 *
 * Why this is needed:
 * - Database cron jobs cannot call Edge Functions due to network restrictions
 * - Jobs are generated by database functions (working)
 * - Jobs need to be executed by Edge Functions (this service bridges the gap)
 */

class AutoBacktestJobMonitor {
  private isMonitoring = false;
  private monitorInterval: NodeJS.Timeout | null = null;
  private readonly CHECK_INTERVAL_MS = 10000; // Check every 10 seconds
  private readonly EDGE_FUNCTION_URL: string;
  private consecutiveErrors = 0;
  private readonly MAX_CONSECUTIVE_ERRORS = 5;

  constructor() {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    this.EDGE_FUNCTION_URL = `${supabaseUrl}/functions/v1/auto-backtest-executor`;
  }

  /**
   * Start monitoring for pending jobs
   */
  async start(userId: string): Promise<void> {
    if (this.isMonitoring) {
      console.log('[Job Monitor] Already monitoring');
      return;
    }

    console.log('[Job Monitor] 🚀 Starting job monitor service...');
    this.isMonitoring = true;
    this.consecutiveErrors = 0;

    // Check immediately
    await this.checkAndExecuteJobs(userId);

    // Then check periodically
    this.monitorInterval = setInterval(async () => {
      await this.checkAndExecuteJobs(userId);
    }, this.CHECK_INTERVAL_MS);
  }

  /**
   * Stop monitoring
   */
  stop(): void {
    console.log('[Job Monitor] 🛑 Stopping job monitor service...');
    this.isMonitoring = false;

    if (this.monitorInterval) {
      clearInterval(this.monitorInterval);
      this.monitorInterval = null;
    }
  }

  /**
   * Check if monitoring is active
   */
  isActive(): boolean {
    return this.isMonitoring;
  }

  /**
   * Check for pending jobs and trigger executor if found
   */
  private async checkAndExecuteJobs(userId: string): Promise<void> {
    if (!this.isMonitoring) return;

    try {
      // Check for pending jobs
      const { data: pendingJobs, error } = await supabase
        .from('auto_backtest_queue')
        .select('id, session_name, status')
        .eq('user_id', userId)
        .eq('status', 'pending')
        .limit(1);

      if (error) {
        console.error('[Job Monitor] Error checking queue:', error);
        this.handleError();
        return;
      }

      if (!pendingJobs || pendingJobs.length === 0) {
        // No pending jobs, reset error counter
        if (this.consecutiveErrors > 0) {
          console.log('[Job Monitor] ✅ No pending jobs, system healthy');
        }
        this.consecutiveErrors = 0;
        return;
      }

      // Found pending jobs, trigger executor
      console.log(`[Job Monitor] 📋 Found ${pendingJobs.length} pending job(s), triggering executor...`);
      await this.triggerExecutor();

      // Reset error counter on success
      this.consecutiveErrors = 0;

    } catch (err) {
      console.error('[Job Monitor] Exception in checkAndExecuteJobs:', err);
      this.handleError();
    }
  }

  /**
   * Trigger the auto-backtest-executor Edge Function
   */
  private async triggerExecutor(): Promise<void> {
    const { data: { session } } = await supabase.auth.getSession();

    if (!session) {
      console.warn('[Job Monitor] No active session, cannot trigger executor');
      return;
    }

    try {
      console.log('[Job Monitor] 🎯 Calling executor Edge Function...');

      const response = await fetch(this.EDGE_FUNCTION_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${session.access_token}`
        },
        body: JSON.stringify({})
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('[Job Monitor] Executor returned error:', response.status, errorText);
        throw new Error(`Executor failed with status ${response.status}`);
      }

      const result = await response.json();
      console.log('[Job Monitor] ✅ Executor completed:', result);

      if (result.processed > 0) {
        console.log(`[Job Monitor] 🎉 Successfully processed ${result.processed} job(s)`);
      }

    } catch (err) {
      console.error('[Job Monitor] Error triggering executor:', err);
      throw err;
    }
  }

  /**
   * Handle errors with backoff
   */
  private handleError(): void {
    this.consecutiveErrors++;

    if (this.consecutiveErrors >= this.MAX_CONSECUTIVE_ERRORS) {
      console.error(`[Job Monitor] ❌ Too many consecutive errors (${this.consecutiveErrors}), stopping monitor`);
      this.stop();
    } else {
      console.warn(`[Job Monitor] ⚠️  Error ${this.consecutiveErrors}/${this.MAX_CONSECUTIVE_ERRORS}, continuing...`);
    }
  }

  /**
   * Get current status
   */
  getStatus(): { isMonitoring: boolean; consecutiveErrors: number } {
    return {
      isMonitoring: this.isMonitoring,
      consecutiveErrors: this.consecutiveErrors
    };
  }
}

export const autoBacktestJobMonitor = new AutoBacktestJobMonitor();
