/**
 * Omega Thresholds Configuration - SSOT
 *
 * Central configuration for all deterministic Omega thresholds.
 * Changing values here affects all deterministic Omega decisions.
 *
 * VERSION: 1.0.0
 */

export const OMEGA_CONFIG_VERSION = '1.0.0';

export const TREND_THRESHOLDS = {
  EMA_SLOPE_STRONG: 0.15,
  EMA_SLOPE_WEAK: 0.05,
  ALIGNMENT_STRONG: 70,
  ALIGNMENT_MODERATE: 50,
  MOMENTUM_STRONG: 60,
  MOMENTUM_WEAK: 20,
  MIN_CONFIDENCE_FOR_TRADE: 55
};

export const SCALPER_THRESHOLDS = {
  VWAP_EXTENDED_DISTANCE_ATR: 1.5,
  VWAP_NORMAL_DISTANCE_ATR: 0.5,
  CHASE_RISK_HIGH: 50,
  CHASE_RISK_MEDIUM: 25,
  ENTRY_QUALITY_EXCELLENT: 75,
  ENTRY_QUALITY_GOOD: 60,
  ENTRY_QUALITY_POOR: 40,
  RSI_OVERBOUGHT: 70,
  RSI_OVERSOLD: 30,
  MIN_CONFIDENCE_FOR_TRADE: 55
};

export const CONFIRMATION_THRESHOLDS = {
  SR_PROXIMITY_ATR: 0.5,
  STRUCTURE_ALIGNMENT_STRONG: 80,
  STRUCTURE_ALIGNMENT_WEAK: 50,
  MTF_ALIGNMENT_BONUS: 15,
  PULLBACK_BONUS: 10,
  MIN_CONFIDENCE_FOR_TRADE: 55
};

export const REVERSAL_THRESHOLDS = {
  RSI_EXTREME_HIGH: 75,
  RSI_EXTREME_LOW: 25,
  DIVERGENCE_STRONG_BONUS: 20,
  DIVERGENCE_MODERATE_BONUS: 10,
  EXHAUSTION_STRONG_BONUS: 15,
  EXHAUSTION_MODERATE_BONUS: 8,
  PATTERN_BONUS: 12,
  MIN_CONFIDENCE_FOR_TRADE: 60
};

export const VOLATILITY_THRESHOLDS = {
  ATR_EXPANSION_HIGH: 1.5,
  ATR_COMPRESSION_LOW: 0.7,
  WICK_RATIO_ERRATIC: 2.0,
  WICK_RATIO_HIGH: 1.5,
  REGIME_FAVORABLE_MAX: 1.3,
  REGIME_FAVORABLE_MIN: 0.8,
  MIN_CONFIDENCE_FOR_TRADE: 50
};

export const CONFLUENCE_THRESHOLDS = {
  STRONG_AGREEMENT: 5,
  MODERATE_AGREEMENT: 4,
  WEAK_AGREEMENT: 3,
  SPLIT_PENALTY: 10,
  DISSENT_HIGH_CONFIDENCE: 70,
  MIN_VOTES_FOR_DIRECTION: 3,
  WEIGHT_TREND: 1.2,
  WEIGHT_SCALPER: 0.9,
  WEIGHT_CONFIRMATION: 1.1,
  WEIGHT_REVERSAL: 1.0,
  WEIGHT_VOLATILITY: 0.8,
  MIN_DOMINANCE_RATIO: 0.2,
  MIN_CONSENSUS_CONFIDENCE: 45
};

export const REGIME_THRESHOLDS = {
  STRONG_TREND_THRESHOLD: 60,
  WEAK_TREND_THRESHOLD: 30,
  RANGING_ATR_RATIO_MAX: 0.8,
  EXTREME_VOL_ATR_RATIO: 2.0,
  HIGH_VOL_ATR_RATIO: 1.3,
  LOW_VOL_ATR_RATIO: 0.7,
  MIN_CONFIDENCE_FOR_TRADE: 50
};

export const ORDERFLOW_THRESHOLDS = {
  STRONG_BULLISH_SCORE: 30,
  NEUTRAL_THRESHOLD: 10,
  MIN_CONFIDENCE_FOR_TRADE: 55,
  SWEEP_WITH_BOS_BONUS: 15,
  FVG_POINTS_PER_GAP: 10,
  VOL_SPIKE_POINTS: 10,
  CONFLUENCE_BONUS_THRESHOLD: 3
};

export const RISK_GATE_THRESHOLDS = {
  MAX_TOTAL_EXPOSURE: 10.0,
  MIN_RR_RATIO: 1.0,
  IDEAL_RR_RATIO: 1.5,
  MIN_SL_ATR: 0.5,
  MAX_SL_ATR: 3.0,
  MIN_SL_PIPS: 5,
  MAX_SPREAD_RISK_PCT: 20,
  CORRELATION_CAP: 0.7
};

export const HALLUCINATION_THRESHOLDS = {
  MIN_TP_DISTANCE_PIPS: 5,
  MIN_SL_DISTANCE_PIPS: 3,
  MAX_RR_RATIO: 10,
  MIN_RR_RATIO: 0.5
};

export function getConfigVersionHash(): string {
  return `v${OMEGA_CONFIG_VERSION}`;
}
