import React from 'react';
import { X, AlertTriangle } from 'lucide-react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function DisclaimerModal({ isOpen, onClose }: DisclaimerModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/70" onClick={onClose} />
      <div className="relative bg-gray-900 rounded-lg max-w-4xl w-full max-h-[90vh] overflow-hidden shadow-2xl border border-amber-700">
        <div className="sticky top-0 bg-gray-900 border-b border-amber-700 p-6 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <AlertTriangle className="text-amber-500" size={28} />
            <h2 className="text-2xl font-bold text-white">Risk Disclaimer</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-white transition-colors p-2 hover:bg-gray-800 rounded"
            aria-label="Close"
          >
            <X size={24} />
          </button>
        </div>

        <div className="overflow-y-auto max-h-[calc(90vh-120px)] p-6 text-gray-300 space-y-6">
          <p className="text-sm text-gray-400">Last Updated: January 20, 2026</p>

          <div className="bg-amber-500/10 border border-amber-500 rounded-lg p-4">
            <p className="text-amber-400 font-semibold">
              PipnosisAi LLC ("Pipnosis," "we," "us," or "our") provides an artificial intelligence-powered trading analysis and signal platform for educational and informational purposes only.
            </p>
          </div>

          <section>
            <h3 className="text-xl font-bold text-white mb-3">No Financial Advice</h3>
            <p>Pipnosis is not a registered investment advisor (RIA), broker-dealer, financial advisor, or commodity trading advisor. Nothing provided by Pipnosis constitutes financial, investment, legal, or tax advice.</p>
            <p className="mt-2">All information, analysis, signals, alerts, and outputs generated by Pipnosis are general in nature and not personalized to any individual's financial situation, objectives, or risk tolerance.</p>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3">No Trade Execution</h3>
            <p>Pipnosis:</p>
            <ul className="list-disc ml-6 mt-2 space-y-2">
              <li>Does not place trades on behalf of users</li>
              <li>Does not connect to or integrate with brokerage accounts</li>
              <li>Does not manage funds or portfolios</li>
            </ul>
            <p className="mt-3 font-semibold text-emerald-400">All trading decisions, order placement, and execution are performed solely by the user on third-party platforms of their choosing.</p>
          </section>

          <section className="bg-red-500/10 border border-red-500 rounded-lg p-4">
            <h3 className="text-xl font-bold text-red-400 mb-3 flex items-center gap-2">
              <AlertTriangle size={24} />
              Risk Disclosure
            </h3>
            <p className="text-white">Trading financial instruments — including but not limited to forex, cryptocurrencies, indices, and commodities — involves substantial risk and is not suitable for all investors. You may lose some or all of your capital.</p>
            <p className="mt-3 font-bold text-red-400">There are no guarantees of profit, and past performance or simulated results do not guarantee future outcomes.</p>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3">AI Limitations</h3>
            <p>Pipnosis uses artificial intelligence and algorithmic systems which:</p>
            <ul className="list-disc ml-6 mt-2 space-y-2">
              <li>May produce incorrect, incomplete, or misleading outputs</li>
              <li>May misinterpret market data or conditions</li>
              <li>Are probabilistic, not deterministic</li>
              <li>May be affected by data delays, outages, or system errors</li>
            </ul>
            <p className="mt-3 font-semibold text-amber-400">AI-generated content should never be relied upon as the sole basis for any trading decision.</p>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3">User Responsibility</h3>
            <p>You acknowledge and agree that:</p>
            <ul className="list-disc ml-6 mt-2 space-y-2">
              <li>You are solely responsible for all trades you place</li>
              <li>You assume full responsibility for any profits or losses</li>
              <li>Pipnosis bears no liability for trading outcomes resulting from your use of the platform</li>
            </ul>
          </section>

          <section>
            <h3 className="text-xl font-bold text-white mb-3">Jurisdiction & Compliance</h3>
            <p>You are responsible for ensuring that your use of Pipnosis complies with all applicable local, state, national, and international laws and regulations.</p>
          </section>

          <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-4 mt-6">
            <p className="text-sm text-gray-400">
              By using Pipnosis, you acknowledge that you have read, understood, and agreed to this disclaimer. If you do not agree with any part of this disclaimer, you must not use the platform.
            </p>
          </div>
        </div>

        <div className="sticky bottom-0 bg-gray-900 border-t border-amber-700 p-6">
          <button
            onClick={onClose}
            className="w-full bg-amber-600 text-white py-3 rounded hover:bg-amber-700 transition-colors font-semibold"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
