/*
  # Enhance AI Learning System with LLM Analysis

  ## Overview
  Add LLM-powered analysis capabilities to the learning system. This enables GPT-4o
  to provide deep pattern insights, strategic recommendations, and confidence calibration
  that goes beyond rule-based analysis.

  ## Changes
  1. Add LLM analysis fields to ai_learning_insights table
  2. Create llm_session_analysis table for storing comprehensive session reviews
  3. Add indexes for LLM-generated insights
  4. Enable realtime subscriptions for live learning updates

  ## Security
  - All tables have RLS policies for user isolation
  - Only authenticated users can read/write their own data
*/

-- ============================================================================
-- STEP 1: Enhance ai_learning_insights with LLM fields
-- ============================================================================

ALTER TABLE ai_learning_insights
ADD COLUMN IF NOT EXISTS llm_generated boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS llm_model_used text,
ADD COLUMN IF NOT EXISTS llm_reasoning text,
ADD COLUMN IF NOT EXISTS llm_improvement_suggestions text[],
ADD COLUMN IF NOT EXISTS learned_from_live_trading boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS learning_weight numeric DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS live_trade_id uuid REFERENCES trade_history(id) ON DELETE CASCADE;

COMMENT ON COLUMN ai_learning_insights.llm_generated IS
'True if this insight was generated by LLM analysis (GPT-4o), false if rule-based';

COMMENT ON COLUMN ai_learning_insights.llm_reasoning IS
'LLM explanation of why this pattern works and the strategic reasoning behind it';

COMMENT ON COLUMN ai_learning_insights.llm_improvement_suggestions IS
'Actionable suggestions from LLM on how to improve this pattern';

COMMENT ON COLUMN ai_learning_insights.learned_from_live_trading IS
'True if this insight came from live demo trading (weighted 2x higher)';

COMMENT ON COLUMN ai_learning_insights.learning_weight IS
'Weight multiplier for this insight (live trades = 2.0, synthetic = 1.0)';

-- ============================================================================
-- STEP 2: Create LLM Session Analysis table
-- ============================================================================

CREATE TABLE IF NOT EXISTS llm_session_analysis (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Session Reference
  backtest_session_id uuid REFERENCES backtest_sessions(id) ON DELETE CASCADE,
  synthetic_session_id uuid REFERENCES synthetic_backtest_sessions(id) ON DELETE CASCADE,

  -- LLM Model Info
  llm_model_used text NOT NULL,

  -- Overall Assessment
  overall_assessment text NOT NULL,
  strengths_identified text[] NOT NULL,
  weaknesses_identified text[] NOT NULL,

  -- Pattern Discovery
  patterns_discovered_count integer NOT NULL DEFAULT 0,

  -- Strategic Guidance
  strategic_recommendations text[] NOT NULL,
  confidence_calibration_advice text NOT NULL,
  next_session_focus text[] NOT NULL,
  estimated_improvement_potential text,

  -- Quality Metrics
  analysis_quality_score integer CHECK (analysis_quality_score >= 0 AND analysis_quality_score <= 100),
  processing_time_ms integer,

  -- Tracking
  was_applied boolean DEFAULT false,
  improvement_after_application numeric,

  created_at timestamptz DEFAULT now(),

  CONSTRAINT unique_session_analysis UNIQUE(user_id, backtest_session_id, synthetic_session_id)
);

-- ============================================================================
-- STEP 3: Create indexes for LLM insights
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_ai_learning_insights_llm_generated
ON ai_learning_insights(llm_generated) WHERE llm_generated = true;

CREATE INDEX IF NOT EXISTS idx_ai_learning_insights_live_trading
ON ai_learning_insights(learned_from_live_trading) WHERE learned_from_live_trading = true;

CREATE INDEX IF NOT EXISTS idx_ai_learning_insights_learning_weight
ON ai_learning_insights(learning_weight DESC);

CREATE INDEX IF NOT EXISTS idx_llm_session_analysis_user
ON llm_session_analysis(user_id);

CREATE INDEX IF NOT EXISTS idx_llm_session_analysis_created
ON llm_session_analysis(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_llm_session_analysis_quality
ON llm_session_analysis(analysis_quality_score DESC);

-- ============================================================================
-- STEP 4: Row Level Security for llm_session_analysis
-- ============================================================================

ALTER TABLE llm_session_analysis ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own LLM analysis"
  ON llm_session_analysis FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create own LLM analysis"
  ON llm_session_analysis FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own LLM analysis"
  ON llm_session_analysis FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- STEP 5: Enable realtime for llm_session_analysis table only
-- ============================================================================

DO $$
BEGIN
  -- Only add llm_session_analysis if not already in publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
    AND tablename = 'llm_session_analysis'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE llm_session_analysis;
  END IF;
END $$;

-- ============================================================================
-- STEP 6: Create view for LLM learning effectiveness
-- ============================================================================

CREATE OR REPLACE VIEW llm_learning_effectiveness AS
SELECT
  user_id,
  COUNT(*) as total_llm_analyses,
  AVG(analysis_quality_score) as avg_quality_score,
  SUM(patterns_discovered_count) as total_patterns_discovered,
  COUNT(*) FILTER (WHERE was_applied = true) as times_applied,
  AVG(improvement_after_application) as avg_improvement,
  AVG(processing_time_ms) as avg_processing_time_ms
FROM llm_session_analysis
GROUP BY user_id;

-- ============================================================================
-- STEP 7: Create function to get most impactful LLM insights
-- ============================================================================

CREATE OR REPLACE FUNCTION get_most_impactful_llm_insights(p_user_id uuid, p_limit integer DEFAULT 10)
RETURNS TABLE(
  insight_id uuid,
  insight_title text,
  insight_description text,
  confidence_score numeric,
  win_rate numeric,
  learning_weight numeric,
  times_applied integer,
  success_rate_when_applied numeric,
  llm_reasoning text
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    ali.id as insight_id,
    ali.insight_title,
    ali.insight_description,
    ali.confidence_score,
    ali.win_rate,
    ali.learning_weight,
    ali.times_applied,
    ali.success_rate_when_applied,
    ali.llm_reasoning
  FROM ai_learning_insights ali
  WHERE ali.user_id = p_user_id
    AND ali.llm_generated = true
  ORDER BY
    (ali.confidence_score * ali.win_rate * ali.learning_weight * COALESCE(ali.success_rate_when_applied, 50)) DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- STEP 8: Add comments for documentation
-- ============================================================================

COMMENT ON TABLE llm_session_analysis IS
'Stores comprehensive LLM-powered analysis of trading sessions. GPT-4o analyzes patterns,
identifies strengths/weaknesses, and provides strategic recommendations for improvement.';

COMMENT ON FUNCTION get_most_impactful_llm_insights IS
'Returns the most impactful LLM-generated insights ranked by confidence, win rate,
learning weight, and success rate when applied. Used to prioritize which insights
to apply in future trading decisions.';
